# Site settings
title: ZWW Blog
SEOTitle: 张威的博客 | zhangweiwei Blog
shareTitle: "@张威的博客 | zhangweiwei Blog"
header-img: img/home-bg.jpg
email: 512932926@qq.com
description: "关于前端与设计、页面仔 | 张魏魏 | 这里是张威个人博客，与你一起发现更大的世界。"
keyword: "张威,张魏魏, 张威的博客, zww Blog, 博客, 个人网站, 互联网, 前端, 设计, 产品,"
baseurl: ""
url: "http://tianzi77.github.io"


# SNS settings
RSS: false
weibo_username:     3782080907
#zhihu_username:     huxpro
github_username:    tianzi77
twitter_username:  tianzi77
facebook_username:  tianzi77


# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true      # if you want to customize anchor. check out line:129 of `post.html`

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM        # use Github Flavored Markdown !important


# Duoshuo settings
# please set your own DuoShuo account in `post.html` and `about.html`
useDuoshuo: true    # use both Comment and Share
useShare: true      # use Comment only. seeing the Share component is depend on Comment so we can NOT use share only.


# Todo: Analysis settings
# Please set your own analysis account in `head.html`(Baidu) and `default.html`(QQ)
useBaiduAnalysis: true
useTencentAnalysis: true
useGoogleAnalysis: true     # TODO


# Sidebar settings
sidebar: true
sidebar-featured-tags: true
sidebar-about-description: "写写代码，做做设计，看看商界。游泳资深玩家，拜仁死忠。"
sidebar-avatar: /img/avatar-hux.jpg     # use absolute URL.

# Friends
friends: [
    {
        title: "腾讯博客",
        href: "http://512932926.qzone.qq.com/"
    },{
        title: "csdn",
        href: "http://blog.csdn.net/u011263845"
    }
]
